# Element-wise Operations

## 1. Addition

### 1.1 Adding a value to each element in  the array

In [1]:
import numpy as np

In [2]:
#creating an array using numpy
arr1 = np.array([[1,2,3],[4,5,6]])
#adding a value to each element in the array
arr1 = np.array(arr1)+2
arr1

array([[3, 4, 5],
       [6, 7, 8]])

### 1.2 Adding 2 matrices to each other

In [3]:
arr2 = np.array ([[1,2,5],[6,7,2]])
arr3 = np.array ([[6,2,1],[7,3,2]])
arr4 = arr2 + arr3
arr4

array([[ 7,  4,  6],
       [13, 10,  4]])

#### NOTE: To add 2 matrices to each other, they should have the same dimensions.

##   
## 2. Element-wise multiplication

### 2.1 Multiplying each value in the array by a value

In [4]:
arr5 = np.array ([[1,2,9],[2,6,3]])
arr5 = np.array (arr5)*2
arr5

array([[ 2,  4, 18],
       [ 4, 12,  6]])

In [5]:
#Using multiply function 
arr5 = np.multiply (arr5,0.5)
arr5

array([[1., 2., 9.],
       [2., 6., 3.]])